Hosts:
  core-api:     :38001
  rbac-api:     :38002
  msg-api:      :38003
  asset-api:    :38004
  snapiq-api:   :19100
  core-ev:      :38051
  rbac-ev:      :38052
  msg-ev:       :38053
  asset-ev:     :38054
  integration:  :53012
Connections:
  default:
    #Txt: "mongodb://localhost:27017/rayidb"
    Txt: "postgres://rayi-user:PasswordRayi@localhost:5432/snapiq?sslmode=disable"
    PoolSize: 25000
    Timeout: 30
    UseTx: false
  rbac:
    #Txt: "mongodb://localhost:27017/rayidb"
    Txt: "postgres://rayi-user:PasswordRayi@localhost:5432/snapiq?sslmode=disable"
    PoolSize: 25000
    Timeout: 30
    UseTx: false
  tenant:
    #Txt: "mongodb://localhost:27017/rayidb"
    Txt: "postgres://rayi-user:PasswordRayi@localhost:5432/snapiq?sslmode=disable"
    PoolSize: 5
    Timeout: 10
    UseTx: false
Services:
  core-api:
    ServerType: Rest
    Provider: kaos-http-deployer
    Secret: "Strong_secret_2025"
    Timeout: 30
    ParamType: default-mux
    Data:
  #msg
  msg-api:
    ServerType: Rest
    Provider: kaos-http-deployer
    Secret: "Strong_secret_2025"
    Timeout: 30
    ParamType: default-mux
    Data:
  # rbac
  rbac-api:
    ServerType: Rest
    Provider: kaos-http-deployer
    Secret: "Strong_secret_2025"
    Timeout: 30
    ParamType: default-mux
    Data:
  rbac-ev:
    ServerType: Event
    Provider: event-http-deployer
    Secret: "Strong_secret_2025"
    Timeout: 30
    ParamType: func 
    Data:
      require_validation: true
  # asset
  asset-api:
    ServerType: Rest
    Provider: kaos-http-deployer
    Secret: "Strong_secret_2025"
    Timeout: 30
    ParamType: default-mux
    Data:
      default-db-connection: tenant
  asset-event:
    ServerType: Event
    Provider: event-http-deployer
    Secret: "Strong_secret_2025"
    Timeout: 30
    ParamType: func
    Data:
      default-db-connection: tenant
  # snapiq
  snapiq-api:
    ServerType: Rest
    Provider: kaos-http-deployer
    Secret: "Strong_secret_2025"
    Timeout: 30
    ParamType: default-mux
    Data:
      default-db-connection: tenant
  # cxo event
  integration:
    ServerType: Event
    Provider: event-http-deployer
    Secret: "Strong_secret_2025"
    Timeout: 30
    ParamType: func 
    Data:
      require_validation: true
Data: 
  cxo_title: CXO
  htev_main: http://localhost:38090
  host_base_path: "http://localhost:38000"
  jwt_secret: "Passwordku_Sangat_Angel_Untuk_Dipecahkan_2025"
  jwt_duration: 1800
  sha_key: "Passwordku_Sangat_Angel_Untuk_Dipecahkan_2025"
